### PR TITLE
Change to own plugin

### PR DESCRIPTION
**Pull request by olliestanley**

### CODE REVIEW

**Comment by olliestanley** [comment]
dun dun dun

**Comment by macalinao** [comment]
Ok so this branch is now officially the "devel" branch that we're going to base the first release off of.

**Comment by macalinao** [comment]
Any HostedFFA commands that are covered by /arena need to be moved into MattMG. We want the default HostedFFA implementation to be as bare as possible.

**Comment by macalinao** [comment]
Ok so #5 and #6 are now covered. Not sure if I want to completely proceed with #7.

**Comment by macalinao** [comment]
Yeah #7 can be done in a different PR. I'm going to merge this now.

**Pull request merged**
