### PR TITLE
Winners

### PR DESCRIPTION
**Pull request by macalinao**
@DziNeIT This is how you make a PR

### CODE REVIEW

**Comment by macalinao** [comment]
Now we can discuss these changes if we wanted to

**Comment by olliestanley** [comment]
'If we wanted to'

We do, right? Is this good? Are changes required? What changes? Answer these, go.

**Comment by macalinao** [comment]
I think Winner should be an abstract class. A HostedFFA should only have one winner, so you'd implement a Winner.getPlayer. I'll write the corresponding code eventually if I can remember to.

**Comment by olliestanley** [comment]
https://github.com/simplyianm/cloudgame/commit/1f20f31fdcf36da86a8ad57ba73439a9d0dfd74c

Hows this? (btw it isn't implemented into the HostedFFA code yet or anything)

**Comment by olliestanley** [comment]
I still be waiting Ian

**Comment by macalinao** [comment]
You don't need to add the list in the abstract class, just an abstract `message()` method i guess

**Comment by olliestanley** [comment]
OK, will do

**Comment by olliestanley** [comment]
Well this is interesting to say the least...

**Comment by olliestanley** [comment]
Basically because of method calls elsewhere, removing the winners list means you need a lot more abstract methods than just 'message()'

**Comment by olliestanley** [comment]
Is it better like this though? It does make it more customisable, but more complex for the implementation of Winner

**Comment by olliestanley** [comment]
Anyway, see latest commit and tell me what you think

**Comment by macalinao** [comment]
You don't need those other methods. You are only using those methods in HostedFFA, so you can put those methods in HostedFFAWinner.

**Comment by olliestanley** [comment]
good point

**Comment by olliestanley** [comment]
Made those changes

**Comment by olliestanley** [comment]
Done

**Pull request merged**
